version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: yt_clone_tweeter
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432